name: Terraform CI

on:
  push:
    branches:
      - main
    paths:
      - "ai-healthcare-terraform/**"
      - ".github/workflows/**"

  pull_request:
    branches:
      - main
    paths:
      - "ai-healthcare-terraform/**"
      - ".github/workflows/**"
concurrency:
  group: terraform-${{ github.repository }}
  cancel-in-progress: false

env:
  TF_WORKDIR: ai-healthcare-terraform

permissions:
  contents: read
  id-token: write

jobs:
  terraform-checks:
    name: terraform checks 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKDIR }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: terraform setup
        uses: hashicorp/setup-terraform@v4
      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      - name: check aws configuration
        run: aws sts get-caller-identity
      - name: terraform format
        run: terraform fmt -check
      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ env.TF_WORKDIR }}
          soft_fail: true # FOR TESTING ONLY
          framework: terraform
      - name: terraform intialization
        run: terraform init
      - name: terraform validate
        run: terraform validate
  terraform-plan:
    needs: terraform-checks
    name: terraform plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKDIR }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: terraform setup
        uses: hashicorp/setup-terraform@v4
      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      - name: check aws configuration
        run: aws sts get-caller-identity
      - name: terraform init
        run: terraform init
      - name: terraform plan command
        run: terraform plan -out=tfplan
      - name: upload plan artifact
        uses: actions/upload-artifact@v7
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKDIR }}/tfplan
  terraform-apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: terraform-plan
    name: terraform apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKDIR }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: terraform setup
        uses: hashicorp/setup-terraform@v4
      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      - name: check aws configuration
        run: aws sts get-caller-identity
      - name: terraform init
        run: terraform init
      - name: download terraform artifact
        uses: actions/download-artifact@v8
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKDIR }}
      - name: terraform apply command
        run: terraform apply -auto-approve tfplan

